version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:7.0.3-alpine
    container_name: redis-cache
    command: redis-server --save 20 1 --loglevel warning --requirepass ${POSTGRES_PASSWORD}
    ports:
      - "6379:6379"

  sso-service:
    build:
      context: .
      dockerfile: Dockerfile.sso
    container_name: sso-service
    depends_on:
      - db
    env_file:
      - apps/sso-service/.env.dev
    ports:
      - "5051:5051"

  talent-service:
    build:
      context: .
      dockerfile: Dockerfile.talent
    container_name: talent-service
    depends_on:
      - db
      - sso-service
    env_file:
      - apps/talent-service/.env.dev
    ports:
      - "5052:5052"

  bff-service:
    build:
      context: .
      dockerfile: Dockerfile.bff
    container_name: bff-service
    restart: always
    depends_on:
      - db
      - cache
      - sso-service
      - talent-service
    env_file:
      - apps/bff-service/.env.dev
    ports:
      - "5050:5050"

volumes:
  dbdata:
  cache:
