# Dockerfile.bff
FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install

COPY . .
RUN pnpm build @apps/bff-service

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist/apps/bff-service ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/bff-service/package.json ./
EXPOSE 5050
CMD ["node", "dist/main.js"]
