# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

# Build the application
RUN pnpm build @apps/bff-service

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/bff-service ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/bff-service/package.json ./

ENV NODE_ENV=production

EXPOSE 8080

CMD ["node", "dist/main.js"]